using Content.Client.ConfigurationUI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Game.UI;

[GenerateTypedNameReferences]
public sealed partial class ContentGame : UIScreen
{
    [Dependency] private readonly ConfigurationUIManager _configuration = default!;
    
    public ContentGame()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("transform_view_enabled", false)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("pause_render", false)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("render_shitty_skybox", true)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("render_draw_parallel", false)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("render_parallel_triangle", false)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("render_debug", false)));
        ConfContainer.AddChild(_configuration.GetOrCreateContainer(new ConfigurationItem<bool>("render_lighting", true)));
    }
}