using Content.Client.Game;
using Robust.Client.AutoGenerated;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenu : UIScreen
{
    [Dependency] private readonly IStateManager _stateManager = default!;
    public MainMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        PlayButton.OnPressed += PlayButtonPressed;
    }

    private void PlayButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _stateManager.RequestStateChange<GameState>();
    }
}