using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenu : UIScreen
{
    public MainMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}