using Content.Client.Game;
using Content.Client.GameTicking;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenu : UIScreen
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IBaseClient _baseClient = default!;
    public MainMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        PlayButton.OnPressed += PlayButtonPressed;
        ConnectButton.OnPressed += ConnectButtonPressed;
    }

    private void ConnectButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _baseClient.ConnectToServer("localhost",1212);
    }

    private void PlayButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _baseClient.StartSinglePlayer();
        Timer.Spawn(0,()=> 
            _entityManager.System<ClientGameTicker>().StartSinglePlayer());
    }
}