global using System;
global using System.Collections.Generic;
global using Robust.Shared.Analyzers;
global using Robust.Shared.Log;
global using Robust.Shared.Localization;
global using Robust.Shared.GameObjects;
global using Robust.Shared.IoC;
global using Robust.Shared.Maths;
global using Robust.Shared.ViewVariables;
global using Robust.Shared.Serialization.Manager.Attributes;
global using Vector3 = System.Numerics.Vector3;
global using Vector4 = System.Numerics.Vector4;
global using Quaternion = System.Numerics.Quaternion;