- type: location
  id: default
  playerSpawn: 
    entity: alexandra
    position: 0,6,12
    rotation: 0,180,0
  entities:
    - entity: floor
      position: 0,-2,0
    - entity: machine
      position: 0,5,0
    - entity: machine
      position: 1,2,3
      rotation: 0,45,0
    - entity: machine
      position: -1,0,6
      rotation: 0,-45,0
    - entity: alexandra
      position: 5,15,5
    - entity: pistol
      position: 3,0,8
    - entity: sword
      position: 5,0,8