- type: location
  id: default
  playerSpawn: 
    entity: alexandra
    position: 0,6,12
    rotation: 0,180,0
  entities:
    - entity: floor
      position: 0,-2,0
    - entity: room
      position: 0,-1,0
    - entity: pistol
      position: 3,0,8
    - entity: sword
      position: 5,0,8